/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AppInfo {
  /** 句柄 */
  hwndId: number
  /** 窗口标题 */
  title: string
  /** MacOS bundleId */
  bundleId: string
  /** 是否激活 */
  isActive: boolean
  /** 目录路径 */
  dir: string
  /** 执行程序路径 */
  exec: string
  /** 当前系统 */
  platform: Platform
}

export declare function getOsExploreInfo(): AppInfo

export declare function getTargetTriple(): string

export declare function initCustomTraceSubscriber(traceOutFilePath?: string | undefined | null): void

export declare const enum Platform {
  unknown = 'unknown',
  windows = 'windows',
  macos = 'macos'
}
